import { ArrivalNoticeRecord } from '@/types/arrival-notice';

export const MOCK_ARRIVAL_NOTICES: ArrivalNoticeRecord[] = [
  {
    id: '1',
    vvd: 'OOCL001/0725N',
    blNo: 'OOCL202400001234',
    deliveryTerm: 'CIF',
    cntrType: '20FT HC',
    del: 'Shanghai',
    podEta: '2024-08-15',
    availableDate: '2024-08-16',
    lastFreeDate: '2024-08-30',
    pickupYard: 'SHICT/CFS',
    returnYard: 'SHICT',
    formType: 'EDI',
    remark: 'Urgent shipment - fragile goods',
    customerCode: 'CUST-SH-001',
    customerName: 'Shanghai Trading Co., Ltd',
    customerAddress: '123 Zhongshan Road, Shanghai, China',
    matchStatus: 'Matched',
    confidenceScore: 98,
    contactEmail: 'customs@shanghatrading.com',
    contactFax: '+86-21-5000-0000',
    status: 'PENDING',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '2',
    vvd: 'MSC-GULSANA/0726N',
    blNo: 'MSC202400005678',
    deliveryTerm: 'FOB',
    cntrType: '40FT STD',
    del: 'Ningbo',
    podEta: '2024-08-18',
    availableDate: '2024-08-19',
    lastFreeDate: '2024-09-02',
    pickupYard: 'NBCT',
    returnYard: 'NBCT',
    formType: 'EDI',
    remark: 'Electronics - requires careful handling',
    customerCode: 'CUST-NB-002',
    customerName: 'Ningbo Electronics Import',
    customerAddress: '456 Qiaogang Road, Ningbo, China',
    matchStatus: 'AI_Suggested',
    confidenceScore: 87,
    suggestedCode: 'CUST-NB-001',
    contactEmail: 'logistics@nbelectronics.com',
    contactFax: '+86-574-8888-0000',
    status: 'PENDING',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '3',
    vvd: 'EVERGREEN/0724E',
    blNo: 'EVERGREEN2024009999',
    deliveryTerm: 'CIP',
    cntrType: '20FT STD',
    del: 'Xiamen',
    podEta: '2024-08-12',
    availableDate: '2024-08-13',
    lastFreeDate: '2024-08-27',
    pickupYard: 'XIAMEN CY',
    returnYard: 'XIAMEN CY',
    formType: 'Paper',
    remark: 'Standard shipment',
    customerCode: 'CUST-XM-003',
    customerName: 'Xiamen Import-Export Co.',
    customerAddress: '789 Lujiang Road, Xiamen, China',
    matchStatus: 'Unmatched',
    confidenceScore: 65,
    contactEmail: 'info@xiamentrading.com',
    contactFax: '+86-592-5555-0000',
    status: 'PENDING',
    lastUpdated: new Date().toISOString(),
  },
];

export const getMockRecordByBlNo = (blNo: string): ArrivalNoticeRecord | undefined => {
  return MOCK_ARRIVAL_NOTICES.find((r) => r.blNo === blNo);
};

export const getAllMockRecords = (): ArrivalNoticeRecord[] => {
  return MOCK_ARRIVAL_NOTICES;
};
