import { ArrivalNoticeRecord } from '@/types/arrival-notice';

export const MOCK_ARRIVAL_NOTICES: ArrivalNoticeRecord[] = [
  {
    id: '1',
    bookingNo: 'SELBK3645303',
    vvd: 'HODT0010E',
    tVvd: 'HODT0010E',
    blNo: 'OOCL202400001234',
    shipperCode: 'SE JUNG SHIPPING CO., LTD',
    shipperName: 'SE JUNG SHIPPING CO., LTD',
    shipperAddress: '123 Port Road, Shanghai, China',
    consigneeName: 'Shanghai Trading Co., Ltd',
    consigneeAddress: '123 Zhongshan Road, Shanghai, China',
    deliveryTerm: 'CIF',
    cntrType: '20FT HC',
    del: 'Shanghai',
    pod: 'Shanghai Port',
    pol: 'Los Angeles',
    podEta: '2024-08-15',
    sailDate: '2026-05-20',
    availableDate: '2024-08-16',
    lastFreeDate: '2024-08-30',
    cyYard: 'SHICT',
    pickupYard: 'SHICT/CFS',
    returnYard: 'SHICT',
    formType: 'EDI',
    volume: 'D2-1.00',
    cargoNature: 'General Cargo',
    remark: 'Urgent shipment - fragile goods',
    customerCode: 'CUST-SH-001',
    customerName: 'Shanghai Trading Co., Ltd',
    customerAddress: '123 Zhongshan Road, Shanghai, China',
    matchStatus: 'Matched',
    confidenceScore: 98,
    contactEmail: 'customs@shanghatrading.com',
    contactFax: '+86-21-5000-0000',
    status: 'PENDING',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '2',
    bookingNo: 'SELBK3645304',
    vvd: 'HODT0010E',
    tVvd: 'HODT0010E',
    blNo: 'MSC202400005678',
    shipperCode: 'SE JUNG SHIPPING CO., LTD',
    shipperName: 'SE JUNG SHIPPING CO., LTD',
    shipperAddress: '456 Harbor Road, Ningbo, China',
    consigneeName: 'Ningbo Electronics Import',
    consigneeAddress: '456 Qiaogang Road, Ningbo, China',
    deliveryTerm: 'FOB',
    cntrType: '40FT STD',
    del: 'Ningbo',
    pod: 'Ningbo Port',
    pol: 'Los Angeles',
    podEta: '2024-08-18',
    sailDate: '2026-05-20',
    availableDate: '2024-08-19',
    lastFreeDate: '2024-09-02',
    cyYard: 'NBCT',
    pickupYard: 'NBCT',
    returnYard: 'NBCT',
    formType: 'EDI',
    volume: 'D2-1.00',
    cargoNature: 'Electronics',
    remark: 'Electronics - requires careful handling',
    customerCode: 'CUST-NB-002',
    customerName: 'Ningbo Electronics Import',
    customerAddress: '456 Qiaogang Road, Ningbo, China',
    matchStatus: 'AI_Suggested',
    confidenceScore: 87,
    suggestedCode: 'CUST-NB-001',
    contactEmail: 'logistics@nbelectronics.com',
    contactFax: '+86-574-8888-0000',
    status: 'PENDING',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '3',
    bookingNo: 'SELG23590801',
    vvd: 'SEQT2618E',
    tVvd: 'SEQT2618E',
    blNo: 'EVERGREEN2024009999',
    shipperCode: 'UNICO TRADE CO LTD',
    shipperName: 'UNICO TRADE CO LTD',
    shipperAddress: '789 Trade Center, Xiamen, China',
    consigneeName: 'TSL LOGISTICS CO., LTD',
    consigneeAddress: '789 Lujiang Road, Xiamen, China',
    deliveryTerm: 'CIP',
    cntrType: '20FT STD',
    del: 'Xiamen',
    pod: 'Xiamen Port',
    pol: 'Los Angeles',
    podEta: '2024-08-12',
    sailDate: '2026-05-18',
    availableDate: '2024-08-13',
    lastFreeDate: '2024-08-27',
    cyYard: 'XIAMEN CY',
    pickupYard: 'XIAMEN CY',
    returnYard: 'XIAMEN CY',
    formType: 'Paper',
    volume: 'D5-1.00',
    cargoNature: 'General Cargo',
    remark: 'Standard shipment',
    customerCode: 'CUST-XM-003',
    customerName: 'Xiamen Import-Export Co.',
    customerAddress: '789 Lujiang Road, Xiamen, China',
    matchStatus: 'Unmatched',
    confidenceScore: 65,
    contactEmail: 'info@xiamentrading.com',
    contactFax: '+86-592-5555-0000',
    status: 'PENDING',
    lastUpdated: new Date().toISOString(),
  },
];

export const getMockRecordByBlNo = (blNo: string): ArrivalNoticeRecord | undefined => {
  return MOCK_ARRIVAL_NOTICES.find((r) => r.blNo === blNo);
};

export const getAllMockRecords = (): ArrivalNoticeRecord[] => {
  return MOCK_ARRIVAL_NOTICES;
};
